### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by danielbalagula** [mattlisiv/newsapi-python#1]
https://newsapi.org/docs/client-libraries/python

Following example:
```
# /v2/everything
all_articles = newsapi.get_everything(q='bitcoin',
                                      sources='bbc-news,the-verge',
                                      domains='bbc.co.uk,techcrunch.com',
                                      from_parameter='2017-12-01',
                                      to='2017-12-12',
                                      language='en',
                                      sortBy='relevancy',
                                      page=2)
```

`sortBy` should be `sort_by`

**Comment by mattlisiv** [comment]
Hi @danielbalagula ,
Thanks for pointing that out. Because this is an unofficial repo, I have notified the News API team to update their documentation. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by News-API-gh** [comment]
@danielbalagula Hey Daniel, thanks for highlighting this. The documentation has just been updated on our site. 👍 👍

**Comment by mattlisiv** [comment]
Thanks News API team. Closing.
