### ISSUE TITLE
Can't mix "Country/Category" with "Sources" parameters.

### ISSUE THREAD

**Issue by saidziani** [mattlisiv/newsapi-python#14]
The problem here is, we can't fetch articles using those two parameters (it's very useful).

**Comment by mattlisiv** [comment]
Hi @saidziani, 

I agree this would be helpful. However, this is a limitation of the underlying News API. If the functionality is added to the API, I will reopen this issue until the wrapper provides the ability to mix the parameters.

If it is critical functionality, I would suggest reaching out to the official News API team (https://newsapi.org/docs) .

Thanks!
