### ISSUE TITLE
Category missing

### ISSUE THREAD

**Issue by Odianosen25** [mattlisiv/newsapi-python#2]

**Comment by Odianosen25** [comment]
Hello Matt,

Thanks for your API and it looks great. Please you left out the category section of the api, so I can't use it when specifying category like business, entertainment and the like. Please can you correct this?

Thanks

**Comment by mattlisiv** [comment]
Thanks for finding that! I'll have the category parameter added and released within the next couple of days.

**Comment by mattlisiv** [comment]
This should now be corrected in version 0.0.2 . If you are using pip, you can update via:

```python
pip install --upgrade newsapi-python
```

**Comment by Odianosen25** [comment]
Many thanks @mattlisiv
