### ISSUE TITLE
Issue with Page

### ISSUE THREAD

**Issue by kushal3553** [mattlisiv/newsapi-python#21]
How do I get all the results as opposed to just 20? When I retrieve results it says I have 1404, but I only get 20 of the articles in the articles section of the dictionary. I know it says to use the page parameter but that does not seem to rectify the issue.

**Comment by mattlisiv** [comment]
Hi @kushal3553 ,

The 1404 is the number of results. It is not possible to retrieve all of these results at once. You can set the pageCount to a max of 100. The best solution is paginate through the results until you reach the amount of records (1404).

Thanks,
Matt
