### ISSUE TITLE
str and unicode

### ISSUE THREAD

**Issue by titocosta** [mattlisiv/newsapi-python#23]
In order to work properly with parameters passed as unicode strings, the correct way to check if a parameter is a string in Python 2.x in `newsapi_client.py` is:

`if isinstance(q, basestring)`

instead of:

`if type(q) == str`

`basestring` includes both `str` and `unicode`.

See [python docs](https://docs.python.org/2/howto/unicode.html#the-unicode-type) for reference.

**Comment by mattlisiv** [comment]
Hi @titocosta ,

Thanks for reporting this. I will add to add this as an enhancement. 

Matt

**Comment by mattlisiv** [comment]
Completed with #40
