### ISSUE TITLE
ES country code missing in const.countries

### ISSUE THREAD

**Issue by titocosta** [mattlisiv/newsapi-python#28]
I noticed that const.countries array is missing code 'es', while the API does return news sources for Spain.

**Comment by mattlisiv** [comment]
@titocosta,

Based on the current documentation, Spain is not a valid country while 'es' is a valid language.

The 2-letter ISO 3166-1 code of the country you want to get headlines for. 

Possible options: ae ar at au be bg br ca ch cn co cu cz de eg fr gb gr hk hu id ie il in it jp kr lt lv ma mx my ng nl no nz ph pl pt ro rs ru sa se sg si sk th tr tw ua us ve za . 

Note: you can't mix this param with the sources param.
