### ISSUE TITLE
ImportError: cannot import name 'NewsApiClient' from 'newsapi'

### ISSUE THREAD

**Issue by sachin2404** [mattlisiv/newsapi-python#29]
I install with newsapi with pip command but it gives an Import error.
what is the solution for this??
One more::I tried to install this newsapi with anaconda promp
command::"conda install -c kvedala newsapi-python" also it gives and error.

**Comment by vonbetelgeuse** [comment]
Getting the same issue in Visual Studio 2017: namespace name "NewsAPI" could not be found
Nuget Package Manager confirms API is installed

**Comment by sachin2404** [comment]
Didn't getting what you want to say

**Comment by sachin2404** [comment]
It is solved : use "from newsapi.newsapi_client import NewsApiClient"

**Comment by jiteshjitsun** [comment]
Again this problem occurring

**Comment by ayushhsinghh** [comment]
same Issue Again.

**Comment by jiteshjitsun** [comment]
first install newsapi module by using -
**pip install newsapi-python**

then modify :-
**from newsapi.newsapi_client import NewsApiClient**
