### ISSUE TITLE
Pagesize is missing

### ISSUE THREAD

**Issue by Risgn94** [mattlisiv/newsapi-python#3]
Hi, and thank you very much for this API!

In the method get_everything in newsapi_client class, there is currently no parameter taking pagesize. Since it is possible through the utilization of Curl, implementing this in the Python library also, would be of great value, so you do not need to look through so many pages.

Best regards

**Comment by mattlisiv** [comment]
Hi @Risgn94 ,

Thanks for pointing out the missing parameter. This should now be corrected in version 0.0.2.
