### ISSUE TITLE
requesting support for python 3.6 and newer 

### ISSUE THREAD

**Issue by omi10859** [mattlisiv/newsapi-python#33]

**Comment by caseyjconger** [comment]
I'm using python 3.6.7 and it works for me (I haven't run through all of the functionality, but basic searches work). The only hiccup was that I had to import it using
`from newsapi.newsapi_client import NewsApiClient`

**Comment by toxicmender** [comment]
Doesn't seem to affect python 3.6.8 on windows 64-bit. I ran the example codes from [NewsAPI site](https://newsapi.org/docs/client-libraries/python).

**Comment by mattlisiv** [comment]
Haven't found any reason why 3.6 does not work. Please open specific issue if you find one.

Thanks!
