### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by vpolimenov** [mattlisiv/newsapi-python#37]
Hello, 

just installed the package and got the following error:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/ff/lib/python3.6/site-packages/newsapi/__init__.py", line 1, in <module>
    from newsapi.newsapi_client import NewsApiClient
  File "/anaconda3/envs/ff/lib/python3.6/site-packages/newsapi/newsapi_client.py", line 12
    def get_top_headlines(self, q=None: str, sources=None: str, language='en': str, country=None: str, category=None: str, page_size=20: int,
                                      ^
SyntaxError: invalid syntax
```

I can see the change coming in from [this](https://github.com/mattlisiv/newsapi-python/pull/34) PR.

Do I need a specific version of something or am I missing something else?

Thanks in advance.

**EDIT:**

Just tested it with version 0.2.3 and I can confirm that it's working. So presumably the whole thing blowed up 2 hours ago, when the version was bumped. 👼

**Comment by davecom** [comment]
Yes, I am running into the same thing on Python 3.7. I believe the issue here is that the type hints with default values are backwards. It should be q: str = None, sources: str = None, etc.

Sorry to bother @mattlisiv again, but it looks like users will need another version bump and this one is more urgent.

**Comment by davecom** [comment]
Also, the PyPI versions of Python that this is compatible with is no longer correct due to the type hints. 3.6, 3.7 should be added and some of the current versions listed should be removed I think.

**Comment by mattlisiv** [comment]
ok my bad. I shouldve paid more attention. I reverted the type hints. Install 0.2.5 and let me know if you still have issues

**Comment by davecom** [comment]
Thanks, @mattlisiv. Things look better.

**Comment by vpolimenov** [comment]
Yes, better! Thank you very much 👍
