### ISSUE TITLE
ImportError: cannot import name 'NewsApiClient'

### ISSUE THREAD

**Issue by fcsimon** [mattlisiv/newsapi-python#5]
Unresolved reference 'NewsApiClient' when attempting to import the client

**Comment by mattlisiv** [comment]
Hi @fcsimon ,

Are you using pip to install the package?

Thanks,
Matt

**Comment by fcsimon** [comment]
Installed via PyCharm's project interpreter

**Comment by fcsimon** [comment]
Tested with Python3 IDE after installing with pip3, works fine. However, not with PyCharm IDE.

**Comment by blitu12345** [comment]
I m also facing the same error on Ubuntu 16.04 pip3!

**Comment by sachin2404** [comment]
Installation error occurred while installing with anaconda prompt.
command::"conda install -c kvedala newsapi-python" gives an error

**Comment by jstuart3** [comment]
> from newsapi.newsapi_client import NewsApiClient

This worked for me. Thanks, man!

**Comment by BarryDeCicco** [comment]
brij1823's method worked for me!

**Comment by pullynnhah** [comment]
You have to install from newsapi-python not newsapi

**Comment by vulongtran** [comment]
I just had this error too.

 _ModuleNotFoundError: No module named 'newsapi'_

I managed to get it working by running this command in my main django folder. 
pip install newsapi-python

**Comment by salonysonawa123** [comment]
> You have to install from newsapi-python not newsapi

thanks , it work for me

**Comment by devindatt** [comment]
brij1823's suggestion worked, awesome thank you!
cli install:  `pip3 install newsapi`
notebook command: _`from newsapi.newsapi_client import NewsApiClient`_

**Comment by vigneshss16** [comment]
> Use this ,it may work:
> 
> from newsapi.newsapi_client import NewsApiClient

**Comment by vigneshss16** [comment]
It worked thank you.

**Comment by krishna-vinci** [comment]
if you ever get this error try: from newsapi import *
it will import everything.
just make sure right pip: pip install newsapi-python
