### ISSUE TITLE
German news broker (spiegel-online Zeit) not working

### ISSUE THREAD

**Issue by StephsGit** [mattlisiv/newsapi-python#57]
After working flawlessly for month I am not getting any news when setting source to 'spiegel-online' or 'die-zeit'. cnn or reuters is still working fine.

**Comment by mattlisiv** [comment]
@StephsGit , this library is solely a wrapper for the API, and unfortunately, this issue seems to be a result of missing content from the API. I would suggest contacting the official News API team to provide more clarity on the available sources.
