### ISSUE TITLE
v2/everything - multiple keywords 

### ISSUE THREAD

**Issue by sputnik44** [mattlisiv/newsapi-python#61]
Hi there,

I tried using multiple keywords but nomatter how I join them, I'm not receiving results any close to what I receive when I use the classic GogleNews Search.
My code:

```
from newsapi import NewsApiClient
api = NewsApiClient(api_key='xxx')
keywords = ['Neubau', 'Weiße', 'Stadt']
all_articles = api.get_everything(q=','.join(keywords),
                                  sort_by='publishedAt',
                                  language='de')
```
besides ',' I tried joining the keywords by:
- '&'
- '%20'
- '%2C'

Is there something I miss?

**Comment by Bitsy-Chuck** [comment]
@sputnik44 I see you marked this as completed.... What was the solution. Getting results which are nowhere close to the keywords provided by me
