### ISSUE TITLE
The base example get_top_headlines() doesn't work.

### ISSUE THREAD

**Issue by clone95** [mattlisiv/newsapi-python#64]
raise ValueError("cannot mix country/category param with sources param.")

**Comment by Gwanghyeon** [comment]
Which language are you using? Did you copy and paste from _usage_ under Client libraries > _one of languages_ and run script? Running newsapi.get_sources() and newsapi.get_top_headlines() at the same time won't work and throw error like below:

```
  File "/Users/gwanghyeongim/Documents/py/freeCodeCamp/api_craigdennis/.venv/lib/python3.7/site-packages/newsapi/newsapi_client.py", line 105, in get_top_headlines
    raise ValueError("cannot mix country/category param with sources param.")
ValueError: cannot mix country/category param with sources param.
```

**Comment by thankblitz** [comment]
Is this fixed? I see the same error too. Any updates on this?

**Comment by mattlisiv** [comment]
Per the NewsAPI documentation: `Note: you can't mix this param with the country or category params.` . 
This library enforces the above rule. 

The package is not directly affiliated with the NewsAPI organization, so I would recommend using the example on the README, as I have no ability to update the site's examples.

**Comment by SYK-08** [comment]
### Python Code
>import config
>from newsapi import NewsApiClient

>newsapi = NewsApiClient(api_key=config.api_key)

>top_headlines = newsapi.get_top_headlines(q='Neuralink',sources='the-verge',category='technology',language='en',country='us')

When I run this code it shows  the Error: *ValueError: cannot mix country/category param with sources param*
How to fix this?
