### ISSUE TITLE
Enum field checking

### ISSUE THREAD

**Issue by TomFaulkner** [mattlisiv/newsapi-python#8]
Some of the fields have a limited set of strings that are acceptable, such as category, country, or language. It would probably be more user friendly if these were checked for validity before being passed to the API.

Enums would also be possible, though that could make for more work on the library user depending on how they are writing their code, and could also be a breaking change.

**Comment by banta-isaiah** [comment]
Can this issue be closed since I addressed it with my PR?

**Comment by mattlisiv** [comment]
That is correct. Closing. Thanks!
